from typing import Any, List, Optional, Tuple

import sage.structure.sage_object


class CharacterArt(sage.structure.sage_object.SageObject):
    def __init__(self,
                 lines: Optional[List[str]] = ...,
                 breakpoints: Optional[List[int]] = ...,
                 baseline: Optional[int] = None,
                 atomic: Optional[Any] = None
                 ) -> None: ...

    @classmethod
    def empty(cls) -> Any: ...

    def get_baseline(self) -> int: ...
    def get_breakpoints(self) -> List[int]: ...
    def height(self) -> int: ...
    def split(self, post: int) -> Tuple[Any, Any]: ...
    def width(self) -> int: ...
